
version: '3'

services:
    zabbix-mysql:
      image: mysql:5.6
      container_name: zabbix-mysql
      ports:
        - '3306:3306'
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      volumes:
        - ./mysql-data:/var/lib/mysql
    zabbix-server:
      image: zabbix/zabbix-server-mysql:ubuntu-3.0.4
      container_name: zabbix-server
      environment:
        DB_SERVER_HOST: "zabbix-mysql"
        MYSQL_USER: root
        MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ports:
        - '10051:10051'
      links:
        - zabbix-mysql
      depends_on:
        - zabbix-mysql
    zabbix-web:
      image: zabbix/zabbix-web-nginx-mysql:ubuntu-3.0.4
      container_name: zabbix-web
      environment:
        DB_SERVER_HOST: zabbix-mysql
        MYSQL_USER: root
        MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ZBX_SERVER_HOST: "zabbix-server"
        PHP_TZ: America/Tegucigalpa
      ports:
        - '80:80'
        - '443:443'
      links:
        - zabbix-mysql
        - zabbix-server
      depends_on:
        - zabbix-mysql
        - zabbix-server
      secrets:                    # secrets block only for 'web' service
      - my_external_secret
      - my_file_secret

secrets:                        # top level secrets block
  my_external_secret:
    external: true
  my_file_secret:
    file: my_file_secret.txt